### ISSUE TITLE
ES6 Issue with Node 14 LTS

### ISSUE THREAD

**Issue by kenodressel** [MRVMV/sequelize-mig#244]
Hey, I stumbled upon your great project. Thanks for picking up this niche issue.

# ISSUE
When I run any command it fails with: 
```
  argv.es6 ??= type === 'module';
           ^^^

SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
```
I assume this is because of the changes introduced in https://github.com/mrvmv/sequelize-mig/commit/fef2c10678a220e0df4879f39f1547f129320a2a

# MY ENV
- Node: v14.15.4
- npm: 7.6.0
- yarn: 1.22.5
- sequelize-mig: 3.1.1

**Comment by mmahalwy** [comment]
Same here :)

**Comment by YukiKAJIHARA** [comment]
Same problem on node v14.13.0.
I reinstall sequelize-mig@3.0.0 and it works nicely.

<Error Message>
node/node_modules/sequelize-mig/bin/migration/make.js:52
  argv.es6 ??= type === 'module';

**Comment by MRVMV** [comment]
Hey guys!
Oh I think it's too easy to solve...
But I don't have any time bcs of uni and work to open my pc to push a commit to solve it 😂
I will be too happy to merge a pull request (from my mobile) if someone introduce it :)

**Comment by MRVMV** [comment]
To help more a little I will mention this article
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment
Its node requirements is 15.0.0
And this absolutely Show a problem with Github Actions which builds successfully even I think it should not do we should solve this too...
Anyway I think we can replace this statement
``` argv.es6 ??= type === 'module';
with
``` argv.es6 = argv.es6 || (type === 'module');
Please anyone willing to to make a PR try this first because I don't have a pc in my hands in these days...
Thx everyone :)
